name: CI Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  starting:
    name: Starting
    runs-on: "ubuntu-latest"

    steps:
      - name: Log a simple message
        run: echo "Hello, GitHub Actions!"

  tests:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - name: Run tests
        run: echo "Running tests..."

