name: CI Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  starting:
    name: Starting
    runs-on: "ubuntu-latest"

    steps:
      - name: Log a simple message
        run: echo "Hello, GitHub Actions!"

  build:
    name: Build
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Build solution
        run: dotnet build -c Debug

      - name: Run tests
        run: dotnet test -c Debug --no-build --no-restore

